# Generated by Django 5.1.7 on 2025-03-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_alter_usuario_options_alter_usuario_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
